name: Main
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.16.x"
      - name: Install dependencies (based on lock file)
        run: npm ci
      - name: Run test
        run: npm test